FROM node:11.3 AS builder

WORKDIR /usr/src/app

COPY package*.json ./
COPY ./src src
COPY ./tests tests
COPY tsconfig.json .
COPY ./tools tools

RUN npm install && npm run build

CMD ["node", "build/src/index.js"]